# Generated by Django 5.2 on 2025-06-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Supplier company name", max_length=200),
                ),
                (
                    "contact_person",
                    models.CharField(
                        help_text="Primary contact person", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary email address", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Primary phone number", max_length=20),
                ),
                ("address", models.TextField(help_text="Full address")),
                ("city", models.CharField(default="", max_length=100)),
                ("state", models.CharField(default="", max_length=100)),
                ("postal_code", models.CharField(default="", max_length=20)),
                ("country", models.CharField(default="", max_length=100)),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="Tax identification number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Company website", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Fair"),
                            (3, "3 - Good"),
                            (4, "4 - Very Good"),
                            (5, "5 - Excellent"),
                        ],
                        help_text="Supplier performance rating",
                        null=True,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        help_text="Payment terms (e.g., Net 30)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Credit limit amount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the supplier",
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "ordering": ["name"],
            },
        ),
    ]
