services:
  db:
    image: postgres:17-alpine
    container_name: kitchen_management_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: kitchen_management
      POSTGRES_USER: kitchen_user
      POSTGRES_PASSWORD: kitchen_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kitchen_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kitchen_user -d kitchen_management"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
    driver: local