services:
  db:
    image: postgres:16
    container_name: kitchen_management_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: kitchen_management
      POSTGRES_USER: kitchen_user
      POSTGRES_PASSWORD: kitchen_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kitchen_user -d kitchen_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kitchen.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local