# Generated by Django 5.2 on 2025-04-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('pcs', 'Pieces'), ('box', 'Box'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter')], max_length=50),
        ),
    ]
