# Generated by Django 5.2 on 2025-05-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='status',
        ),
    ]
