# Generated by Django 5.2 on 2025-05-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_preparation_steps_recipe_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='nutritional_info',
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Total calories (kcal)', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grams of carbs', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fats',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grams of fat', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grams of fiber', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='proteins',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grams of protein', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sodium',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Milligrams of sodium', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sugar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grams of sugar', max_digits=5, null=True),
        ),
    ]
